# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-08 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstores', '0002_store_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='file',
            field=models.TextField(max_length=20971520),
        ),
    ]
