web:
  image: django:1.9
  volumes:
    - .:/usr/src/app
  working_dir: /usr/src/app
  command: python manage.py runserver 0.0.0.0:8000
  ports:
    - 8080:8000
  environment:
    - VIRTUAL_HOST=stores.spistresci.pl
    - VIRTUAL_PORT=8000

